# Change these first
owner: gscsre # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository
user-agent: gscsre

sites:
  - name: San Cristobal
    url: https://www.sancristobal.com.ar/institucional
  - name: Soporte Pas
    url: https://soportepas.sancristobal.com.ar
  - name: San Cristobal Retiro
    url: https://www.sancristobalretiro.com.ar
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  theme: dark
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Prod
  introTitle: "**Uptime**"
  introMessage: Hope is not a strategy
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
